[ tool.poetry ]
name = "fast-inertia"
version = "0.1.0"
description = "FastAPI project with Poetry"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[ tool.poetry.dependencies ]
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.27.0"}
pydantic = "^2.6.0"
pydantic-settings = "^2.1.0"
python-multipart = "^0.0.9"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}

[ tool.poetry.group.dev.dependencies ]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
black = "^24.1.0"
ruff = "^0.2.0"
httpx = "^0.26.0"
pytest-asyncio = "^0.23.0"

[ tool.poetry.scripts ]
dev = "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
start = "uvicorn app.main:app --host 0.0.0.0 --port 8000"


[ build-system ]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[ tool.ruff ]
select = ["E", "F", "I", "B", "C4", "ARG", "SIM", "PLR"]
ignore = ["E501"]
line-length = 88

[ tool.ruff.isort ]
known-first-party = ["app"]
combine-as-imports = true

[ tool.pytest.ini_options ]
testpaths = ["tests"]
addopts = "--cov=app --cov-report=term-missing"
asyncio_mode = "auto"

[ tool.coverage.run ]
source = ["app"]
omit = ["tests/*"]

[ tool.coverage.report ]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
    "if TYPE_CHECKING:",
]